<?php
/**
 * Copyright 2006 - 2013 Eric D. Hough (http://ehough.com)
 *
 * This file is part of coauthor (https://github.com/ehough/coauthor)
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 */
namespace Ehough\Bundle\PagodaBoxBundle\CacheWarmer;

use Symfony\Component\HttpKernel\CacheWarmer\CacheWarmerInterface;

/**
 * Warms up the form cache.
 *
 * This warmer must be registered after TemplatePathsCacheWarmer,
 * as the Twig loader will need the cache generated by it.
 *
 * @author Fabien Potencier <fabien@symfony.com>
 */
class TwigBridgeTemplateWarmer implements CacheWarmerInterface
{
    private static $_TEMPLATES = array('div', 'table');

    /**
     * @var \Twig_Environment
     */
    private $_twigEnvironment;

    public function __construct(\Twig_Environment $twigEnvironment)
    {
        $this->_twigEnvironment = $twigEnvironment;
    }

    /**
     * Warms up the cache.
     *
     * @param string $cacheDir The cache directory
     */
    public function warmUp($cacheDir)
    {
        foreach (self::$_TEMPLATES as $template) {

            $this->_warmBridgeTemplate($template);
        }
    }

    private function _warmBridgeTemplate($name)
    {
        try {

            $this->_twigEnvironment->loadTemplate('form_' . $name . '_layout.html.twig');
        
        } catch (\Twig_Error $e) {

            return;
        }
    }

    /**
     * Checks whether this warmer is optional or not.
     *
     * @return Boolean always true
     */
    public function isOptional()
    {
        return true;
    }
}
